/*******************************************************************************
 * BotFather (C) - Dofus 1.29 protocol library
 * This class is part of an AresRPG Project.
 *
 * @author Sceat {@literal <sceat@aresrpg.fr>}
 * @author Duarte David {@literal <deltaduartedavid@gmail.com>}
 * 
 *         Created 2016
 *******************************************************************************/
package fr.aresrpg.dofus.structures;

/**
 * 
 * @since
 */
public enum Skills {
	// si tu veut t'amuser a traduire tout en anglais vas y
	ACHETER_MAISON(97),
	UTILISER_ENCLO(175),
	ACHETER_ENCLOS(176),
	ACTIONNER(179),
	PUISER(102),
	AMELIORER_BOTTES(163),
	AMELIORER_ANNEAU(168),
	AMELIORER_CHAPEAU(166),
	AMELIORER_SAC(167),
	AMELIORER_AMULETTE(169),
	AMELIORER_CAPE(165),
	AMELIORER_CEINTURE(164),
	BRICOLER(171),
	BRISER_OBJET(181),
	COLLECTER_FER(24),
	COLLECTER_CUIVRE(25),
	COLLECTER_BRONZE(26),
	COLLECTER_KOBALTE(28),
	COLLECTER_ARGENT(29),
	COLLECTER_OR(30),
	COLLECTER_BAUXITE(31),
	COLLECTER_ETEIN(55),
	COLLECTER_MANGANESE(56),
	COLLECTER_DOLOMITE(161),
	COLLECTER_SILICATE(162),
	CONCASSER_RESSOURCES(121),
	CONFECTIONNER_BOTTES(13),
	CONFECTIONNER_CEINTURE(14),
	CONFECTIONNER_CLEF(182),
	CONSULTER(170),
	COUDRE_CHAPEAU(63),
	COUDRE_SAC(123),
	COUDRE_CAPE(64),
	COUPER_FRENE(6),
	COUPER_CHENE(10),
	COUPER_IF(33),
	COUPER_EBENE(34),
	COUPER_ORME(35),
	COUPER_ERABLE(37),
	COUPER_CHARME(38),
	COUPER_CHATAIGNIER(39),
	COUPER_NOYER(40),
	COUPER_MERISIER(41),
	COUPER_BOMBU(139),
	COUPER_OLIVIOLET(141),
	COUPER_BAMBOU(154),
	COUPER_BAMBOU_SOMBRE(155),
	COUPER_BAMBOU_SACRE(158),
	COUPER_KALIPTUS(174),
	CREER_ANNEAU(11),
	CREER_AMULETTE(12),
	CEUILLIR_LIN(68),
	CEUILLIR_CHANVRE(69),
	CEUILLIR_TREFLE(71),
	CEUILLIR_MENTHE(72),
	CEUILLIR_ORCHIDEE(73),
	CEUILLIR_EDELWEISS(74),
	CEUILLIR_GRAINE_PANDOUILLE(160),
	CUIR_PAIN(27),
	DEVEROUILLER(100),
	DEVEROUILLER_2(106),
	EGRENER(122),
	ENTRER(84),
	EPLUCHER(22),
	FAIRE_BIERE(96),
	FAIRE_BONBONS(109),
	FAUCHER_BLE(45),
	FAUCHER_HOUBLON(46),
	FAUCHER_LIN(50),
	FAUCHER_SEIGLE(52),
	FAUCHER_ORGE(53),
	FAUCHER_CHANVRE(54),
	FAUCHER_AVOINE(57),
	FAUCHER_MALT(58),
	FAUCHER_RIZ(159),
	FILER(95),
	FONDRE(32),
	FORGER_BOUCLIER(156),
	FORGER_MARTEAU(19),
	FORGER_DAGUE(18),
	FORGER_EPEE(20),
	FORGER_FAUX(66),
	FORGER_HACHE(65),
	FORGER_PELLE(21),
	FORGER_PIOCHE(67),
	FOUILLER(153),
	INVOQUER_FEE(151),
	JOUER(150),
	MODIFIER_PRIX_VENTE(108),
	MOUDRE(47),
	OUVRIR(104),
	POLIR_PIERRE(48),
	PREPARER(132),
	PREPARER_POISSON(135),
	PREPARER_VIANDE(134),
	PREPARER_POTION(23),
	PECHER_GOUJON(124),
	PECHER_TRUITE(125),
	PECHER_POISSON_CHATON(126),
	PECHER_BROCHET(127),
	PECHER_GREUVETTE(128),
	PECHER_CRABE_SOURIMI(129),
	PECHER_POISSON_PANE(130),
	PECHER_SARDINE_BRILLANTE(131),
	PECHER_PICHON_EUD_COMPET(136),
	PECHER_KRALAMOURE(140),
	PECHER_SARDINE_BRILLANTE_2(189),
	PECHER_KOINKOIN(152),
	RAMASSER(42),
	REFORGER_MARTEAU(116),
	REFORGER_DAGUE(1),
	REFORGER_EPEE(113),
	REFORGER_HACHE(115),
	REFORGER_PELLE(117),
	RESCULPTER_ARC(118),
	RESCULPTER_BATON(120),
	RESCULPTER_BAGUETTE(119),
	REPARER_ARC(149),
	REPARER_BATON(147),
	REPARER_MARTEAU(144),
	REPARER_BAGUETTE(148),
	REPARER_DAGUE(142),
	REPARER_EPEE(145),
	REPARER_HACHE(143),
	REPARER_PELLE(146),
	SAUVEGARDER(44),
	SCIER(101),
	SCULPTER_ARC(15),
	SCULPTER_BATON(17),
	SCULPTER_BAGUETTE(16),
	SE_FAIRE_TRANSPORTER(157),
	SE_RENDRE_INCARNAM(183),
	SE_REGENERER(62),
	SE_REGENERER_2(111),
	SORTIR(187),
	UTILISER(114),
	UTILISER_2(184),
	UTILISER_ETABLI(110),
	VENDRE_MAISON(98),
	VENDRE_ENCLOS(177),
	VEROUILLER_MAISON(81),
	VEROUILLER(105),
	VIDER(133),;

	private int id;

	private Skills(int id) {
		this.id = id;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	public static Skills valueOf(int code) {
		for (Skills i : values())
			if (i.getId() == code) return i;
		return null;
	}

	public static boolean isHarvestSkill(Skills s) {
		switch (s) {
			case COLLECTER_FER:
			case COLLECTER_CUIVRE:
			case COLLECTER_BRONZE:
			case COLLECTER_ARGENT:
			case COLLECTER_KOBALTE:
			case COLLECTER_OR:
			case COLLECTER_BAUXITE:
			case COLLECTER_ETEIN:
			case COLLECTER_MANGANESE:
			case COLLECTER_DOLOMITE:
			case COLLECTER_SILICATE:
			case COUPER_FRENE:
			case COUPER_CHENE:
			case COUPER_IF:
			case COUPER_EBENE:
			case COUPER_ORME:
			case COUPER_ERABLE:
			case COUPER_CHARME:
			case COUPER_CHATAIGNIER:
			case COUPER_NOYER:
			case COUPER_MERISIER:
			case COUPER_BOMBU:
			case COUPER_OLIVIOLET:
			case COUPER_BAMBOU:
			case COUPER_BAMBOU_SOMBRE:
			case COUPER_BAMBOU_SACRE:
			case COUPER_KALIPTUS:
			case CEUILLIR_LIN:
			case CEUILLIR_CHANVRE:
			case CEUILLIR_TREFLE:
			case CEUILLIR_MENTHE:
			case CEUILLIR_ORCHIDEE:
			case CEUILLIR_EDELWEISS:
			case CEUILLIR_GRAINE_PANDOUILLE:
			case FAUCHER_BLE:
			case FAUCHER_HOUBLON:
			case FAUCHER_LIN:
			case FAUCHER_SEIGLE:
			case FAUCHER_ORGE:
			case FAUCHER_CHANVRE:
			case FAUCHER_AVOINE:
			case FAUCHER_MALT:
			case FAUCHER_RIZ:
			case PECHER_GOUJON:
			case PECHER_TRUITE:
			case PECHER_POISSON_CHATON:
			case PECHER_BROCHET:
			case PECHER_GREUVETTE:
			case PECHER_POISSON_PANE:
			case PECHER_CRABE_SOURIMI:
			case PECHER_SARDINE_BRILLANTE:
			case PECHER_PICHON_EUD_COMPET:
			case PECHER_KRALAMOURE:
			case PECHER_SARDINE_BRILLANTE_2:
				return true;
			default:
				return false;
		}
	}

	public static boolean isJobSkill(Skills s) {
		switch (s) {
			case AMELIORER_BOTTES:
			case AMELIORER_ANNEAU:
			case AMELIORER_CHAPEAU:
			case AMELIORER_SAC:
			case AMELIORER_AMULETTE:
			case AMELIORER_CAPE:
			case AMELIORER_CEINTURE:
			case BRICOLER:
			case COLLECTER_FER:
			case COLLECTER_CUIVRE:
			case COLLECTER_BRONZE:
			case COLLECTER_ARGENT:
			case COLLECTER_KOBALTE:
			case COLLECTER_OR:
			case COLLECTER_BAUXITE:
			case COLLECTER_ETEIN:
			case COLLECTER_MANGANESE:
			case COLLECTER_DOLOMITE:
			case COLLECTER_SILICATE:
			case CONFECTIONNER_BOTTES:
			case CONFECTIONNER_CEINTURE:
			case CONFECTIONNER_CLEF:
			case COUDRE_CHAPEAU:
			case COUDRE_SAC:
			case COUDRE_CAPE:
			case COUPER_FRENE:
			case COUPER_CHENE:
			case COUPER_IF:
			case COUPER_EBENE:
			case COUPER_ORME:
			case COUPER_ERABLE:
			case COUPER_CHARME:
			case COUPER_CHATAIGNIER:
			case COUPER_NOYER:
			case COUPER_MERISIER:
			case COUPER_BOMBU:
			case COUPER_OLIVIOLET:
			case COUPER_BAMBOU:
			case COUPER_BAMBOU_SOMBRE:
			case COUPER_BAMBOU_SACRE:
			case COUPER_KALIPTUS:
			case CREER_ANNEAU:
			case CREER_AMULETTE:
			case CEUILLIR_LIN:
			case CEUILLIR_CHANVRE:
			case CEUILLIR_TREFLE:
			case CEUILLIR_MENTHE:
			case CEUILLIR_ORCHIDEE:
			case CEUILLIR_EDELWEISS:
			case CEUILLIR_GRAINE_PANDOUILLE:
			case CUIR_PAIN:
			case EGRENER:
			case FAIRE_BONBONS:
			case FAUCHER_BLE:
			case FAUCHER_HOUBLON:
			case FAUCHER_LIN:
			case FAUCHER_SEIGLE:
			case FAUCHER_ORGE:
			case FAUCHER_CHANVRE:
			case FAUCHER_AVOINE:
			case FAUCHER_MALT:
			case FAUCHER_RIZ:
			case FORGER_BOUCLIER:
			case FORGER_MARTEAU:
			case FORGER_DAGUE:
			case FORGER_EPEE:
			case FORGER_FAUX:
			case FORGER_HACHE:
			case FORGER_PELLE:
			case FORGER_PIOCHE:
			case MOUDRE:
			case POLIR_PIERRE:
			case PREPARER:
			case PREPARER_POISSON:
			case PREPARER_VIANDE:
			case PREPARER_POTION:
			case PECHER_GOUJON:
			case PECHER_TRUITE:
			case PECHER_POISSON_CHATON:
			case PECHER_BROCHET:
			case PECHER_GREUVETTE:
			case PECHER_POISSON_PANE:
			case PECHER_CRABE_SOURIMI:
			case PECHER_SARDINE_BRILLANTE:
			case PECHER_PICHON_EUD_COMPET:
			case PECHER_KRALAMOURE:
			case PECHER_SARDINE_BRILLANTE_2:
			case SCIER:
			case SCULPTER_ARC:
			case SCULPTER_BATON:
			case SCULPTER_BAGUETTE:
				return true;
			default:
				return false;
		}
	}

}
